const ACTIONS = Object.freeze([
  { name: "right_hand_up", label: "右抬手", expression: "right_hand_up", durationMs: 3200, parameters: { Param17: 1 } },
  { name: "left_hand_up", label: "左抬手", expression: "left_hand_up", durationMs: 3200, parameters: { Param267: 1 } },
  { name: "twin_tail", label: "双马尾", expression: "twin_tail", durationMs: 3200, parameters: { Param: 1 } },
  { name: "microphone", label: "麦克风", expression: "microphone", durationMs: 3200, parameters: { Param16: 1 } },
  { name: "finger_heart", label: "比心", expression: "finger_heart", durationMs: 3200, parameters: { Param15: 1 } },
  { name: "gaming", label: "游戏机", expression: "gaming", durationMs: 3200, parameters: { Param14: 1 } },
  { name: "shadow_face", label: "黑脸", expression: "shadow_face", durationMs: 2600, parameters: { Param2: 1 } },
  { name: "cry", label: "哭哭", expression: "cry", durationMs: 2600, parameters: { Param8: 1 } },
  { name: "heart", label: "爱心眼", expression: "heart", durationMs: 2600, parameters: { Param6: 1 } },
  { name: "star_eyes", label: "星星眼", expression: "star_eyes", durationMs: 2600, parameters: { Param7: 1 } },
  { name: "dizzy", label: "晕晕", expression: "dizzy", durationMs: 2600, parameters: { Param5: 1 } },
  { name: "sweat", label: "流汗", expression: "sweat", durationMs: 2600, parameters: { Param11: 1 } },
  { name: "anxious", label: "着急", expression: "anxious", durationMs: 2600, parameters: { Param12: 1 } },
  { name: "angry", label: "生气", expression: "angry", durationMs: 2600, parameters: { Param10: 1 } },
  { name: "blush", label: "脸红", expression: "blush", durationMs: 2600, parameters: { Param3: 1 } },
  { name: "flowers", label: "花花", expression: "flowers", durationMs: 2600, parameters: { Param9: 1 } },
  { name: "question", label: "问号", expression: "question", durationMs: 2600, parameters: { Param13: 1 } },
  { name: "dark_mode", label: "黑化", expression: "dark_mode", durationMs: 2600, parameters: { Param4: 1 } },
  { name: "captain", label: "舰长轮盘", motion: "captain", durationMs: 2600 },
  { name: "admiral", label: "提督轮盘", motion: "admiral", durationMs: 2600 },
  { name: "governor", label: "总督轮盘", motion: "governor", durationMs: 2600 },
  { name: "up", label: "游戏上", expression: "up", durationMs: 1800, parameters: { Param81: 1 } },
  { name: "down", label: "游戏下", expression: "down", durationMs: 1800, parameters: { Param79: 1 } },
  { name: "left", label: "游戏左", expression: "left", durationMs: 1800, parameters: { Param82: 1 } },
  { name: "right", label: "游戏右", expression: "right", durationMs: 1800, parameters: { Param80: 1 } },
  { name: "plus", label: "游戏 Shift", expression: "plus", durationMs: 1800, parameters: { Param85: 1 } },
  { name: "scene1", label: "待机动作", motion: "scene1", durationMs: 2600 },
]);

module.exports = { ACTIONS };
