/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: de6deb372efa7bf78cc5e072dac054aa)
interface __BaseEnv_Env {
	ELF2: Fetcher;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
